openapi: 3.0.3
info:
  title: Application for managing charge stations
  description: Application for managing charge stations
  version: 1.0.0

paths:

  /versions:
    $ref: operation/versions.yaml
  /charge-points/{serialNumber}/connectors:
    $ref: operation/charge-points-id-connector.yaml
  /charging-sessions:
    $ref: operation/charging-sessions.yaml
  /charging-sessions/{sessionId}:
    $ref: operation/charging-sessions-id.yaml

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic