openapi: 3.0.3
info:
  title: Application for managing charge stations
  description: Application for managing charge stations
  version: 1.0.0

paths:

  /versions:
    get:
      operationId: getVersion
      description: "Get application version information"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: 'model/VersionResponseDto.json'