openapi: 3.0.3
info:
  title: Application for managing charge stations
  description: Application for managing charge stations
  version: 1.0.0

paths:

  /versions:
    $ref: operation/versions.yaml
  /charge-points/{serialNumber}/connectors:
    $ref: operation/charge-points-add-connector.yaml
  /charging-sessions:
    $ref: operation/charging-sessions.yaml