### Send PUT request: end charging session
PUT http://localhost:8080/charging-sessions/1
Accept: application/json
Content-Type: application/json
Authorization: Basic smirnova smirnova

{
  "endTime": "2022-01-01T12:30:00",
  "meterValue": 15
}

### Send PUT request: end charging session with error
PUT http://localhost:8080/charging-sessions/2
Accept: application/json
Content-Type: application/json
Authorization: Basic smirnova smirnova

{
  "errorMessage": "Some error"
}