### Send POST request with json body
PUT http://localhost:8080/charging-sessions
Accept: application/json
Content-Type: application/json

{
  "sessionId": "1",
  "dateTime": "2022-01-01T12:30:00",
  "meterValue": 15
}