### Send POST request: start charging session
POST http://localhost:8080/charging-sessions
Accept: application/json
Content-Type: application/json

{
  "rfIdTagNumber": "9382134b-46f1-437f-b581-49c533a49661",
  "pointSerialNumber": "number1",
  "connectorNumber": 1,
  "dateTime": "2022-01-01T12:00:00"
}