version: '3.9'

services:

  charge-stations-app:
    container_name: charge-stations-app
    build: .
    ports:
      - "8080:8080"
      - "8082:8082"
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 5s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - charge-stations-app
    volumes:
      - ./env/prometheus:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./env/grafana/main.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./env/grafana/dashboards:/var/lib/grafana/dashboards
      - ./env/grafana/datasources:/etc/grafana/provisioning/datasources