{
 "title": "execute request",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "start sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "start_session_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "end session",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "end_session_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "get sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "get_charge_sessions_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "create connector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "add_connector_seconds_count", "legendFormat": "__auto" }
   ]
  }
 ]
}