spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:charge-stations
    username: electrical
    password: electrical
  h2:
    console:
      enabled: true
  jpa:
    show_sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none

application:
  version:
    database: 1.0
    application: 1.0