spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:charge-stations
    username: electrical
    password: electrical
  h2:
    console:
      enabled: true
  jpa:
    show_sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    readinessState:
      enabled: true
  server:
    port: 8082

application:
  version:
    database: 1.0
    application: 1.0